# @package _global_.model
name: larger_skip
batch_size: 1

stride: [2, 2, 2]
enc_depths: [2, 2, 2, 2]
enc_channels: [112, 200, 400, 800]
enc_num_head: [2, 4, 8, 16]
enc_patch_size: [1024, 1024, 512, 512]
dec_depths: [2, 2, 2]
# dec_channels[0] = class_subset (injected at runtime); must be divisible by dec_num_head[0]=4
dec_channels_rest: [200, 400]
dec_num_head: [4, 8, 16]
dec_patch_size: [1024, 1024, 512]
enable_flash: true
enable_skip: true
